let API_URL_SUFFIX = '/shortterm'
let API_URL_SUFFIX_V1 = `${API_URL_SUFFIX}`
// 博饼相关API
let API_PANCAKE_GAME_V1 = `${API_URL_SUFFIX_V1}/pancake-game`

const v1 = {
  GET_PANCAKE_GAME_PARAM: `${API_PANCAKE_GAME_V1}/get-index-data`,
  GET_PANCAKE_GAME_ROLL: `${API_PANCAKE_GAME_V1}/roll`,
  GET_PANCAKE_GAME_SHARE: `${API_PANCAKE_GAME_V1}/share`,
  POST_PANCAKE_GAME_RECEIVE_PRIZE: `${API_PANCAKE_GAME_V1}/receive-prize`,
  GET_PANCAKE_GAME_PRIZE_RANKING: `${API_PANCAKE_GAME_V1}/prize-ranking`,
  GET_PANCAKE_GAME_TIMES_RANKING: `${API_PANCAKE_GAME_V1}/times-ranking`,
  GET_PANCAKE_GAME_THUMBUP: `${API_PANCAKE_GAME_V1}/thumbup`,
  GET_PANCAKE_GAME_MY_PRIZE: `${API_PANCAKE_GAME_V1}/my-prize`,
  GET_PANCAKE_GAME_COUPON_LIST: `${API_PANCAKE_GAME_V1}/coupon-list`
}

export {
  v1
}
